# Generated by Django 4.2.8 on 2023-12-15 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('In-Progress', 'In Progress'), ('To Do', 'Todo'), ('Done', 'Done')], default='To Do', max_length=20)),
            ],
            bases=('common.basemodel',),
        ),
    ]
